repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: [--fix, backend/packages]
      - id: ruff-format
        args: [backend/packages]
