services:
  backend:
    build:
      context: ./backend
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: /app/src
        - path: ./backend/alembic
          action: sync
          target: /app/alembic
        - path: ./backend/uv.lock
          action: rebuild
    ports:
      - 8765:8000
    tty: true
    env_file: backend/.env
    environment:
      - DATABASE_HOST=postgres
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hiremepls
    volumes:
      - db_data:/var/lib/postgresql/data:rw
volumes:
  db_data: