services:
  backend:
    container_name: hiremepls-be
    build:
      context: ./backend
      dockerfile: packages/web/Dockerfile
      target: dev
    develop:
      watch:
        - path: ./backend/packages/web
          action: sync
          target: /app/packages/web
        - path: ./backend/uv.lock
          action: rebuild
    ports:
      - 8765:8000
    tty: true
    env_file: backend/.env
    environment:
      - DATABASE_HOST=postgres
      - RUN_MIGRATIONS=true
      - CREATE_ADMIN_USER=true
    depends_on:
      - postgres
    volumes:
      - ./shared/openapi.json:/shared/openapi.json:rw
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hiremepls
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  frontend:
    container_name: hiremepls-fe
    build:
      context: ./frontend
    ports:
      - 8766:5173
    volumes:
      - ./frontend/src:/app/src:rw
    develop:
      watch:
        - path: ./frontend
          ignore:
            - src/
          action: sync
          target: /app
        - path: ./frontend/pnpm-lock.yaml
          action: rebuild
        - path: ./frontend/Dockerfile
          action: rebuild
volumes:
  db_data: