[project]
name = "hiremepls"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.14.1",
    "fastapi[standard]>=0.115.10",
    "loguru>=0.7.3",
    "psycopg[binary]>=3.2.5",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
    "sqlmodel>=0.0.23",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pre-commit>=4.1.0",
    "ruff>=0.9.9",
]

[tool.ruff]
line-length = 100
exclude = ["alembic/"]

[tool.mypy]
strict = true
