[project]
name = "web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.10",
    "lib",
    "pyjwt>=2.10.1",
    "alembic>=1.14.1",
    "google-cloud-tasks>=2.19.2",
]

[tool.uv.sources]
lib = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
