"""add slug to company

Revision ID: 3179cea41117
Revises: fe042a829160
Create Date: 2025-03-12 21:43:24.839714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3179cea41117'
down_revision: Union[str, None] = 'fe042a829160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False), schema='jobs')
    op.create_index(op.f('ix_jobs_company_slug'), 'company', ['slug'], unique=True, schema='jobs')
    op.create_index(op.f('ix_jobs_company_url'), 'company', ['url'], unique=True, schema='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_company_url'), table_name='company', schema='jobs')
    op.drop_index(op.f('ix_jobs_company_slug'), table_name='company', schema='jobs')
    op.drop_column('company', 'slug', schema='jobs')
    # ### end Alembic commands ###
