"""Add date columns to all tables

Revision ID: f26f1c9fd5be
Revises: f31c0e87ff2f
Create Date: 2025-03-12 18:41:00.350869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f26f1c9fd5be'
down_revision: Union[str, None] = 'f31c0e87ff2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), schema='jobs')
    op.add_column('company', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), schema='jobs')
    op.add_column('compensation', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), schema='jobs')
    op.add_column('compensation', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), schema='jobs')
    op.add_column('job', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), schema='jobs')
    op.add_column('job', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), schema='jobs')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), schema='users')
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True), schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at', schema='users')
    op.drop_column('user', 'created_at', schema='users')
    op.drop_column('job', 'updated_at', schema='jobs')
    op.drop_column('job', 'created_at', schema='jobs')
    op.drop_column('compensation', 'updated_at', schema='jobs')
    op.drop_column('compensation', 'created_at', schema='jobs')
    op.drop_column('company', 'updated_at', schema='jobs')
    op.drop_column('company', 'created_at', schema='jobs')
    # ### end Alembic commands ###
