"""make job url unique

Revision ID: fe042a829160
Revises: f26f1c9fd5be
Create Date: 2025-03-12 20:34:46.534886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fe042a829160'
down_revision: Union[str, None] = 'f26f1c9fd5be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_job_job_url'), 'job', ['job_url'], unique=True, schema='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_job_job_url'), table_name='job', schema='jobs')
    # ### end Alembic commands ###
