/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutApplicationsRouteImport } from './routes/_layout/applications/route'
import { Route as LayoutApplicationsIndexImport } from './routes/_layout/applications/index'
import { Route as LayoutApplicationsNewImport } from './routes/_layout/applications/new'
import { Route as LayoutApplicationsApplicationIdImport } from './routes/_layout/applications/$applicationId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRouteRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutApplicationsRouteRoute = LayoutApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutApplicationsIndexRoute = LayoutApplicationsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutApplicationsRouteRoute,
} as any)

const LayoutApplicationsNewRoute = LayoutApplicationsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutApplicationsRouteRoute,
} as any)

const LayoutApplicationsApplicationIdRoute =
  LayoutApplicationsApplicationIdImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => LayoutApplicationsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/applications': {
      id: '/_layout/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof LayoutApplicationsRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/applications/$applicationId': {
      id: '/_layout/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof LayoutApplicationsApplicationIdImport
      parentRoute: typeof LayoutApplicationsRouteImport
    }
    '/_layout/applications/new': {
      id: '/_layout/applications/new'
      path: '/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof LayoutApplicationsNewImport
      parentRoute: typeof LayoutApplicationsRouteImport
    }
    '/_layout/applications/': {
      id: '/_layout/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof LayoutApplicationsIndexImport
      parentRoute: typeof LayoutApplicationsRouteImport
    }
  }
}

// Create and export the route tree

interface LayoutApplicationsRouteRouteChildren {
  LayoutApplicationsApplicationIdRoute: typeof LayoutApplicationsApplicationIdRoute
  LayoutApplicationsNewRoute: typeof LayoutApplicationsNewRoute
  LayoutApplicationsIndexRoute: typeof LayoutApplicationsIndexRoute
}

const LayoutApplicationsRouteRouteChildren: LayoutApplicationsRouteRouteChildren =
  {
    LayoutApplicationsApplicationIdRoute: LayoutApplicationsApplicationIdRoute,
    LayoutApplicationsNewRoute: LayoutApplicationsNewRoute,
    LayoutApplicationsIndexRoute: LayoutApplicationsIndexRoute,
  }

const LayoutApplicationsRouteRouteWithChildren =
  LayoutApplicationsRouteRoute._addFileChildren(
    LayoutApplicationsRouteRouteChildren,
  )

interface LayoutRouteRouteChildren {
  LayoutApplicationsRouteRoute: typeof LayoutApplicationsRouteRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutApplicationsRouteRoute: LayoutApplicationsRouteRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/applications': typeof LayoutApplicationsRouteRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/applications/$applicationId': typeof LayoutApplicationsApplicationIdRoute
  '/applications/new': typeof LayoutApplicationsNewRoute
  '/applications/': typeof LayoutApplicationsIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/': typeof LayoutIndexRoute
  '/applications/$applicationId': typeof LayoutApplicationsApplicationIdRoute
  '/applications/new': typeof LayoutApplicationsNewRoute
  '/applications': typeof LayoutApplicationsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/applications': typeof LayoutApplicationsRouteRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/applications/$applicationId': typeof LayoutApplicationsApplicationIdRoute
  '/_layout/applications/new': typeof LayoutApplicationsNewRoute
  '/_layout/applications/': typeof LayoutApplicationsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/signup'
    | '/applications'
    | '/'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/applications'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/applications'
    | '/_layout/'
    | '/_layout/applications/$applicationId'
    | '/_layout/applications/new'
    | '/_layout/applications/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login",
        "/signup"
      ]
    },
    "/_layout": {
      "filePath": "_layout/route.tsx",
      "children": [
        "/_layout/applications",
        "/_layout/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_layout/applications": {
      "filePath": "_layout/applications/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/applications/$applicationId",
        "/_layout/applications/new",
        "/_layout/applications/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/applications/$applicationId": {
      "filePath": "_layout/applications/$applicationId.tsx",
      "parent": "/_layout/applications"
    },
    "/_layout/applications/new": {
      "filePath": "_layout/applications/new.tsx",
      "parent": "/_layout/applications"
    },
    "/_layout/applications/": {
      "filePath": "_layout/applications/index.tsx",
      "parent": "/_layout/applications"
    }
  }
}
ROUTE_MANIFEST_END */
